@echo off
rem Double-click this file to preview the NZDO website on this computer.
rem It updates the list of photos, then opens the website in your browser.
chcp 65001 >nul
cd /d "%~dp0site"
set "OUT=js\photo-list.js"
> "%OUT%" echo // AUTOMATICALLY GENERATED by "Preview website (Windows).bat" - dont edit by hand.
>> "%OUT%" echo NZDO.photos = {
for /d %%D in (concert_photos\*) do (
  >> "%OUT%" echo  "%%~nxD": [
  for %%F in ("%%D\*.jpg" "%%D\*.jpeg" "%%D\*.png" "%%D\*.webp" "%%D\*.gif") do >> "%OUT%" echo   "%%~nxF",
  >> "%OUT%" echo  ],
)
>> "%OUT%" echo };
start "" "index.html"
