// Writes site/js/photo-list.js: the names of the photos in each site/photos/<folder>/.
//
// A web page can't look inside a folder by itself, so this list tells it which photos exist.
// Cloudflare runs this automatically every time the site is published (see wrangler.jsonc),
// so new photo folders just work. To preview new photos on your own computer, run:
//     node tools/list-photos.mjs

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, extname, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const site = join(dirname(fileURLToPath(import.meta.url)), "..", "site");
const photosDir = join(site, "photos");
const exts = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif"]);

const list = {};
for (const folder of readdirSync(photosDir).sort()) {
  const path = join(photosDir, folder);
  if (!statSync(path).isDirectory()) continue;
  list[folder] = readdirSync(path)
    .filter((f) => !f.startsWith(".") && exts.has(extname(f).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

writeFileSync(
  join(site, "js", "photo-list.js"),
  "// AUTOMATICALLY GENERATED by tools/list-photos.mjs – don't edit by hand.\n" +
    `NZDO.photos = ${JSON.stringify(list, null, 1)};\n`
);

const total = Object.values(list).reduce((n, f) => n + f.length, 0);
console.log(`photo-list.js: ${total} photos in ${Object.keys(list).length} folders`);
