#!/bin/bash
# Writes site/js/photo-list.js: the names of the photos in each site/concert_photos/<folder>/.
#
# A web page can't look inside a folder by itself, so this list tells it which photos exist.
# It runs automatically when you double-click "Preview website (Mac).command", and when
# Cloudflare publishes the site (see wrangler.jsonc). Uses only built-in commands.
# (Windows does the same thing in "Preview website (Windows).bat".)

cd "$(dirname "$0")/../site" || exit 1
shopt -s nullglob nocaseglob

{
  echo "// AUTOMATICALLY GENERATED by tools/make-photo-list.sh – don't edit by hand."
  echo "NZDO.photos = {"
  for dir in concert_photos/*/; do
    folder=$(basename "$dir")
    echo " \"$folder\": ["
    for f in "$dir"*.jpg "$dir"*.jpeg "$dir"*.png "$dir"*.webp "$dir"*.gif; do
      name=$(basename "$f" | sed 's/\\/\\\\/g; s/"/\\"/g')
      echo "  \"$name\","
    done
    echo " ],"
  done
  echo "};"
} > js/photo-list.js

echo "Photo list updated: $(grep -c '^  "' js/photo-list.js) photos in $(grep -c '^ "' js/photo-list.js) folders."
